language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run nosetests
script: nosetests Tests/test_orthologs.py --verbosity=3
