Management_config:
  new_repo: true
  new_user: true
  new_project: true
  new_database: true
  new_research: true
  new_app: false
  new_website: false
  database: 'Test-Database'
  repo: 'Test-Repository'
  user: 'Test-User'
  project: 'Test-Project'
  research: 'Test-Research'
  research_type: 'Test-Research-Type'
  app: 'Test-App'
  website: 'Test-Website'
  host: '0.0.0.0'
  port: '5252'

Database_config:
  email:  "rgilmore@umc.edu"
  driver: "sqlite3"
  ftp_flag: True
  Full:
    configure_flag: False
    archive_flag: False
    delete_flag: False
    project_flag: False
    _path: !!python/object/apply:pathlib.Path ['']
    Projects:
      Project_Name_1:
        configure_flag: False
        archive_flag: False
        delete_flag: False
        _path: !!python/object/apply:pathlib.Path ['Project_Name_1']
      Project_Name_2:
        configure_flag: False
        archive_flag: False
        delete_flag: False
        _path: !!python/object/apply:pathlib.Path ['Project_Name_2']
      Project_Name_3:
        configure_flag: False
        archive_flag: False
        delete_flag: False
        _path: !!python/object/apply:pathlib.Path ['Project_Name_3']
    NCBI:
      configure_flag: False
      archive_flag: False
      delete_flag: False
      _path: !!python/object/apply:pathlib.Path ['NCBI']
      NCBI_blast:
        configure_flag: False
        archive_flag: False
        delete_flag: False
        _path: !!python/object/apply:pathlib.Path ['NCBI', 'blast']
        NCBI_blast_db:
          configure_flag: False
          archive_flag:  False
          delete_flag: False
          _path: !!python/object/apply:pathlib.Path ['NCBI', 'blast', 'db']
        NCBI_blast_windowmasker_files:
          configure_flag: False
          archive_flag: False
          delete_flag: False
          _path: !!python/object/apply:pathlib.Path ['NCBI', 'blast', 'windowmasker_files']
          taxonomy_ids: ""
      NCBI_pub_taxonomy:
        configure_flag: False
        archive_flag: False
        delete_flag: False
        _path: !!python/object/apply:pathlib.Path ['NCBI', 'pub', taxonomy']
      NCBI_refseq_release:
        seqtype: "rna" # Other seqtypes are protein and genomic
        seqformat: "gbff"
        collection_subset: "vertebrate_mammalian"
        activate: !!python/object/apply:pathlib.Path ['~', '.venv', 'OrthoEvol', 'bin', 'activate']
        configure_flag: False
        configure_template: True
        archive_flag: False
        delete_flag: False
        upload_flag: True
        _path: !!python/object/apply:pathlib.Path ['NCBI', 'refseq', 'release']
    ITIS:
      configure_flag: True
      archive_flag: False
      delete_flag: False
      _path: !!python/object/apply:pathlib.Path ['ITIS']
      ITIS_taxonomy:
        configure_flag: True
        archive_flag: False
        delete_flag: False
        _path: !!python/object/apply:pathlib.Path ['ITIS', 'taxonomy']