"""
Description of what this file does.
-----------------------------------------------------------------------
Requirements:
    ncbi-blast+

Usage:

"""

import os

from OrthoEvol.Orthologs.Blast import OrthoBlastN, BaseBlastN

configfile: "config.yaml"

rule blast:
    """Run BLASTn against a given database and write the results to XML."""
    input:
        genes="{accessions}.csv"
    output:
        str(ANNOTATION_FP/'blastn'/'{db}'/'{contigs}'/'{sample}.xml')
    params:
        db=lambda wildcard: Blastdbs['nucl'][wildcard.db]
    log:
        "{log_directory}/blast_run.log"
