"""
Description of what this file does.
-----------------------------------------------------------------------
Requirements:
    ncbi-blast+

Usage:

"""

import csv

from Bio import SearchIO
from xml.etree.ElementTree import ParseError

rule run_blastn:
    """Run BLASTn against a given database and write the results to XML."""
    input:
        contigs=str(ASSEMBLY_FP/'contigs'/'{sample}-contigs.fa')
    output:
        str(ANNOTATION_FP/'blastn'/'{db}'/'{contigs}'/'{sample}.xml')
    params:
        db=lambda wildcard: Blastdbs['nucl'][wildcard.db]
    threads:
        Cfg['blast']['threads']
    shell:
        """
        blastn \
        -query {input.contigs} \
        -db {params.db} \
        -outfmt 5 \
        -num_threads {threads} \
        -evalue 1e-10 \
        -max_target_seqs 1 \
        -out {output} \
        """